
import java.awt.Canvas;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    //Personal Variables Declaration
    static boolean Flag = false;
    static Cancion TempSong = null;
    static Playlist TempPlaylist = null;
    static ArrayList<Cancion> Songs = new ArrayList();

    static ArrayList<Cancion> TempSongs = new ArrayList();
    static ArrayList<Playlist> Playlists = new ArrayList();
    static Cancion Songss = new Cancion();
    static Playlist Playlistss = new Playlist();

    private void resetPersona() {
        this.JT_Album.setText("Album");
        this.JT_Artista.setText("Artista");
        this.JT_NombreSong.setText("Nombre");
        this.JFT_Año.setText("0000");
        this.JCB_Puntos.setSelectedIndex(0);
    }

    private void TablesInit(boolean flag) {
        if (flag == false) {
            File archivo = null;
            Scanner sc = null;
            DefaultTableModel TableModel = (DefaultTableModel) JTa_AllSongs.getModel();
            DefaultTableModel TableModel2 = (DefaultTableModel) JTa_AllSongs2.getModel();
            try {
                archivo = new File("./Files/Canciones/Canciones.txt");
                sc = new Scanner(archivo);
                while (sc.hasNext()) {
                    String[] Next = sc.nextLine().split("\\|");
                    String Nom = Next[0];
                    String Art = Next[1];
                    String Alb = Next[2];
                    String Punt = Next[3];
                    String Ano = Next[4];
                    Object[] Line = {Nom, Art, Alb, Punt, Ano};
                    Songs.add(new Cancion(Nom, Art, Alb, Integer.parseInt(Punt), Integer.parseInt(Ano)));
                    TableModel.addRow(Line);
                    TableModel2.addRow(Line);
                    JTa_AllSongs.setModel(TableModel);
                    JTa_AllSongs2.setModel(TableModel2);
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error en el Reader.");
            }
            sc.close();
        }
        Flag = true;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddSong = new javax.swing.JDialog();
        JT_NombreSong = new javax.swing.JTextField();
        JT_Artista = new javax.swing.JTextField();
        JT_Album = new javax.swing.JTextField();
        JFT_Año = new javax.swing.JFormattedTextField();
        JCB_Puntos = new javax.swing.JComboBox<>();
        JB_3 = new javax.swing.JButton();
        JB_SaveSong = new javax.swing.JButton();
        JB_SaveSongMod = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        ListSong = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        JB_DeleteSong = new javax.swing.JButton();
        JB_EditSong = new javax.swing.JButton();
        JB_NewSong = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTa_AllSongs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        JB_NewPlaylist = new javax.swing.JButton();
        JB_EditPlayList = new javax.swing.JButton();
        JB_DeletePlaylist = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTa_AllPlaylists = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        JB_1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();
        AddPlaylist = new javax.swing.JDialog();
        JT_NombrePlaylsit = new javax.swing.JTextField();
        JB_SavePlaylist = new javax.swing.JButton();
        JB_2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        JB_Song2Playlist = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTa_AllSongs2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        JB_RemoveinPlaylist = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTa_SongsinPlaylist = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();
        JB_AddSong = new javax.swing.JButton();
        JB_AddPlaylist = new javax.swing.JButton();
        JB_ViewPlaylist = new javax.swing.JButton();
        JB_ViewSongs = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        JMI_AbrirCanciones = new javax.swing.JMenuItem();
        JMI_VerCanciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMI_AbrirPlaylist = new javax.swing.JMenuItem();
        JMI_VerPlaylists = new javax.swing.JMenuItem();

        AddSong.setUndecorated(true);
        AddSong.setResizable(false);
        AddSong.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_NombreSong.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        JT_NombreSong.setText("Nombre");
        AddSong.getContentPane().add(JT_NombreSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 50));

        JT_Artista.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        JT_Artista.setText("Artista");
        AddSong.getContentPane().add(JT_Artista, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 200, 50));

        JT_Album.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        JT_Album.setText("Album");
        AddSong.getContentPane().add(JT_Album, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 200, 50));

        try {
            JFT_Año.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_Año.setText("0000");
        JFT_Año.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        AddSong.getContentPane().add(JFT_Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 130, 50));

        JCB_Puntos.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        JCB_Puntos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        AddSong.getContentPane().add(JCB_Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 80, 50));

        JB_3.setBackground(new java.awt.Color(114, 114, 114));
        JB_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_3.setBorder(null);
        JB_3.setBorderPainted(false);
        JB_3.setContentAreaFilled(false);
        JB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_3ActionPerformed(evt);
            }
        });
        AddSong.getContentPane().add(JB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        JB_SaveSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveSong.setBorder(null);
        JB_SaveSong.setBorderPainted(false);
        JB_SaveSong.setContentAreaFilled(false);
        JB_SaveSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveSongActionPerformed(evt);
            }
        });
        AddSong.getContentPane().add(JB_SaveSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, -1));

        JB_SaveSongMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SaveSongMod.setBorder(null);
        JB_SaveSongMod.setBorderPainted(false);
        JB_SaveSongMod.setContentAreaFilled(false);
        JB_SaveSongMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveSongModActionPerformed(evt);
            }
        });
        AddSong.getContentPane().add(JB_SaveSongMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, -1));

        jLabel8.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Puntos");
        AddSong.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 170, 70));

        jLabel11.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Año");
        AddSong.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 170, 70));

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Album");
        AddSong.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 170, 70));

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Artista");
        AddSong.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 170, 70));

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Nombre");
        AddSong.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the-lab.png"))); // NOI18N
        AddSong.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 56)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Agregar Canciones");
        AddSong.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 900, 130));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_hd_169_mesa_mezclas_bn.jpg"))); // NOI18N
        AddSong.getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -360, 1190, 960));

        ListSong.setUndecorated(true);
        ListSong.setResizable(false);
        ListSong.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Songs");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 130, -1));

        JB_DeleteSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        JB_DeleteSong.setBorder(null);
        JB_DeleteSong.setBorderPainted(false);
        JB_DeleteSong.setContentAreaFilled(false);
        JB_DeleteSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DeleteSongActionPerformed(evt);
            }
        });
        jPanel1.add(JB_DeleteSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 440, 57, -1));

        JB_EditSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Edit.png"))); // NOI18N
        JB_EditSong.setBorder(null);
        JB_EditSong.setBorderPainted(false);
        JB_EditSong.setContentAreaFilled(false);
        JB_EditSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EditSongActionPerformed(evt);
            }
        });
        jPanel1.add(JB_EditSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 440, 57, -1));

        JB_NewSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_NewSong.setBorder(null);
        JB_NewSong.setBorderPainted(false);
        JB_NewSong.setContentAreaFilled(false);
        JB_NewSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewSongActionPerformed(evt);
            }
        });
        jPanel1.add(JB_NewSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 440, 57, -1));

        JTa_AllSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Album", "Año", "Puntuacion"
            }
        ));
        jScrollPane5.setViewportView(JTa_AllSongs);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 740, 360));

        jTabbedPane1.addTab("Songs", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_NewPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_NewPlaylist.setBorder(null);
        JB_NewPlaylist.setBorderPainted(false);
        JB_NewPlaylist.setContentAreaFilled(false);
        JB_NewPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_NewPlaylistActionPerformed(evt);
            }
        });
        jPanel2.add(JB_NewPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 440, 57, -1));

        JB_EditPlayList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_EditPlayList.setBorder(null);
        JB_EditPlayList.setBorderPainted(false);
        JB_EditPlayList.setContentAreaFilled(false);
        JB_EditPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EditPlayListActionPerformed(evt);
            }
        });
        jPanel2.add(JB_EditPlayList, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 440, 57, -1));

        JB_DeletePlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Upload.png"))); // NOI18N
        JB_DeletePlaylist.setBorder(null);
        JB_DeletePlaylist.setBorderPainted(false);
        JB_DeletePlaylist.setContentAreaFilled(false);
        JB_DeletePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DeletePlaylistActionPerformed(evt);
            }
        });
        jPanel2.add(JB_DeletePlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 440, 57, -1));

        JTa_AllPlaylists.setBackground(new java.awt.Color(0, 51, 51));
        JTa_AllPlaylists.setForeground(new java.awt.Color(204, 204, 204));
        JTa_AllPlaylists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Album", "Año", "Puntuacion"
            }
        ));
        jScrollPane4.setViewportView(JTa_AllPlaylists);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 740, 360));

        jLabel21.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Playlists:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 190, -1));

        jTabbedPane1.addTab("Playlists", jPanel2);

        ListSong.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 760, 520));

        JB_1.setBackground(new java.awt.Color(114, 114, 114));
        JB_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_1.setBorder(null);
        JB_1.setBorderPainted(false);
        JB_1.setContentAreaFilled(false);
        JB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_1ActionPerformed(evt);
            }
        });
        ListSong.getContentPane().add(JB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("CAnciones/Playslists");
        ListSong.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 860, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the-lab.png"))); // NOI18N
        ListSong.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_hd_169_mesa_mezclas_bn.jpg"))); // NOI18N
        ListSong.getContentPane().add(Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -360, 1190, 960));

        AddPlaylist.setUndecorated(true);
        AddPlaylist.setResizable(false);
        AddPlaylist.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT_NombrePlaylsit.setFont(new java.awt.Font("Imprint MT Shadow", 2, 36)); // NOI18N
        JT_NombrePlaylsit.setText("Playlist");
        AddPlaylist.getContentPane().add(JT_NombrePlaylsit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 50));

        JB_SavePlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        JB_SavePlaylist.setBorder(null);
        JB_SavePlaylist.setBorderPainted(false);
        JB_SavePlaylist.setContentAreaFilled(false);
        JB_SavePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SavePlaylistActionPerformed(evt);
            }
        });
        AddPlaylist.getContentPane().add(JB_SavePlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 57, -1));

        JB_2.setBackground(new java.awt.Color(114, 114, 114));
        JB_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Back.png"))); // NOI18N
        JB_2.setBorder(null);
        JB_2.setBorderPainted(false);
        JB_2.setContentAreaFilled(false);
        JB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_2ActionPerformed(evt);
            }
        });
        AddPlaylist.getContentPane().add(JB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Song2Playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add.png"))); // NOI18N
        JB_Song2Playlist.setBorder(null);
        JB_Song2Playlist.setBorderPainted(false);
        JB_Song2Playlist.setContentAreaFilled(false);
        JB_Song2Playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Song2PlaylistActionPerformed(evt);
            }
        });
        jPanel3.add(JB_Song2Playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 321, 57, -1));

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 2, 24)); // NOI18N
        jLabel19.setText("Agregar a Playlist");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 318, 191, 51));

        JTa_AllSongs2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Album", "Año", "Puntuacion"
            }
        ));
        jScrollPane6.setViewportView(JTa_AllSongs2);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 310));

        jTabbedPane2.addTab("All Songs", jPanel3);

        JB_RemoveinPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        JB_RemoveinPlaylist.setBorder(null);
        JB_RemoveinPlaylist.setBorderPainted(false);
        JB_RemoveinPlaylist.setContentAreaFilled(false);

        jLabel20.setFont(new java.awt.Font("Imprint MT Shadow", 2, 24)); // NOI18N
        jLabel20.setText("Eliminar de Playlist");

        JTa_SongsinPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Album", "Año", "Puntuacion"
            }
        ));
        jScrollPane7.setViewportView(JTa_SongsinPlaylist);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_RemoveinPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_RemoveinPlaylist))
                .addGap(21, 21, 21))
        );

        jTabbedPane2.addTab("Added Songs", jPanel4);

        AddPlaylist.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 430, 420));

        jLabel17.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 51));
        jLabel17.setText("Songs");
        AddPlaylist.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 180, 70));

        jLabel16.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Nombre");
        AddPlaylist.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, 70));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Playslists");
        AddPlaylist.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 440, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the-lab.png"))); // NOI18N
        AddPlaylist.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo_hd_169_mesa_mezclas_bn.jpg"))); // NOI18N
        AddPlaylist.getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -360, 1190, 960));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_AddSong.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        JB_AddSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add big.png"))); // NOI18N
        JB_AddSong.setBorder(null);
        JB_AddSong.setBorderPainted(false);
        JB_AddSong.setContentAreaFilled(false);
        JB_AddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddSongActionPerformed(evt);
            }
        });
        getContentPane().add(JB_AddSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 70, 70));

        JB_AddPlaylist.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        JB_AddPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Add big.png"))); // NOI18N
        JB_AddPlaylist.setBorder(null);
        JB_AddPlaylist.setBorderPainted(false);
        JB_AddPlaylist.setContentAreaFilled(false);
        JB_AddPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AddPlaylistActionPerformed(evt);
            }
        });
        getContentPane().add(JB_AddPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 70, 70));

        JB_ViewPlaylist.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        JB_ViewPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/View.png"))); // NOI18N
        JB_ViewPlaylist.setBorder(null);
        JB_ViewPlaylist.setBorderPainted(false);
        JB_ViewPlaylist.setContentAreaFilled(false);
        JB_ViewPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ViewPlaylistActionPerformed(evt);
            }
        });
        getContentPane().add(JB_ViewPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 70, 70));

        JB_ViewSongs.setFont(new java.awt.Font("Imprint MT Shadow", 2, 48)); // NOI18N
        JB_ViewSongs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/View.png"))); // NOI18N
        JB_ViewSongs.setBorder(null);
        JB_ViewSongs.setBorderPainted(false);
        JB_ViewSongs.setContentAreaFilled(false);
        JB_ViewSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ViewSongsActionPerformed(evt);
            }
        });
        getContentPane().add(JB_ViewSongs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 70, 70));

        jLabel15.setBackground(new java.awt.Color(60, 20, 230));
        jLabel15.setFont(new java.awt.Font("Imprint MT Shadow", 3, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 153));
        jLabel15.setText("Songs");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 200, -1));

        jLabel14.setBackground(new java.awt.Color(60, 20, 230));
        jLabel14.setFont(new java.awt.Font("Imprint MT Shadow", 3, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 153));
        jLabel14.setText("Playlists");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the-lab.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unnamed-1-14.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1101, -1));

        jMenu1.setText("File");

        jMenu2.setText("Canciones");

        JMI_AbrirCanciones.setText("Abrir");
        JMI_AbrirCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_AbrirCancionesActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_AbrirCanciones);

        JMI_VerCanciones.setText("Ver");
        jMenu2.add(JMI_VerCanciones);

        jMenu1.add(jMenu2);

        jMenu3.setText("Playlists");

        JMI_AbrirPlaylist.setText("Abrir");
        jMenu3.add(JMI_AbrirPlaylist);

        JMI_VerPlaylists.setText("Ver");
        jMenu3.add(JMI_VerPlaylists);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddSongActionPerformed
        TablesInit(Flag);
        AddSong.setVisible(true);
        AddSong.pack();
        AddSong.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_AddSongActionPerformed

    private void JB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_2ActionPerformed
        JT_NombrePlaylsit.setVisible(true);
        AddPlaylist.setVisible(false);
        this.setVisible(true);
        this.pack();
    }//GEN-LAST:event_JB_2ActionPerformed

    private void JB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_3ActionPerformed
        AddSong.setVisible(false);
        this.setVisible(true);
        this.pack();
    }//GEN-LAST:event_JB_3ActionPerformed

    private void JB_ViewSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ViewSongsActionPerformed
        TablesInit(Flag);
        ListSong.setVisible(true);
        ListSong.pack();
        ListSong.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_ViewSongsActionPerformed

    private void JB_AddPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AddPlaylistActionPerformed
        TablesInit(Flag);
        AddPlaylist.setVisible(true);
        AddPlaylist.pack();
        AddPlaylist.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_AddPlaylistActionPerformed

    private void JB_ViewPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ViewPlaylistActionPerformed
        TablesInit(Flag);
        ListSong.setVisible(true);
        ListSong.pack();
        ListSong.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_JB_ViewPlaylistActionPerformed

    private void FillTables(JTable Table, ArrayList<Cancion> Songs) {
        DefaultTableModel TabModel = (DefaultTableModel) Table.getModel();
        Object Line[] = {(Object) Songs.get(Songs.size() - 1).getNombre(), (Object) Songs.get(Songs.size() - 1).getArtista(), (Object) Songs.get(Songs.size() - 1).getAlbum(), (Object) Songs.get(Songs.size() - 1).getPuntos(), (Object) Songs.get(Songs.size() - 1).getAño()};
        TabModel.addRow(Line);
    }

    private void JB_SaveSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveSongActionPerformed
        try {
            if (JT_NombreSong.equals("") || JT_Album.equals("") || JT_Artista.equals("")) {
                JOptionPane.showMessageDialog(null, "Error, Complete la información.");
            } else {
                Songss.WriteFile(JT_NombreSong.getText(), JT_Artista.getText(), JT_Album.getText(), Integer.parseInt(JFT_Año.getText()), JCB_Puntos.getSelectedIndex() + 1);
                Songs.add(new Cancion(JT_NombreSong.getText(), JT_Artista.getText(), JT_Album.getText(), Integer.parseInt(JFT_Año.getText()), JCB_Puntos.getSelectedIndex() + 1));
                FillTables(JTa_AllSongs, Songs);
                FillTables(JTa_AllSongs2, Songs);
                resetPersona();
                JOptionPane.showMessageDialog(this, "Guardado Exitoso.");
                resetPersona();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error.");
        }
    }//GEN-LAST:event_JB_SaveSongActionPerformed

    private void JB_SavePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SavePlaylistActionPerformed
        try {
            if (JT_NombrePlaylsit.equals("")) {
                JOptionPane.showMessageDialog(null, "Agregue un Nombre.");
            } else {
                Playlistss.WriteFile(TempSongs, JT_NombrePlaylsit.getText());
                JOptionPane.showMessageDialog(jMenu1, "Guardada");
                JTa_AllSongs2.clearSelection();
                /*for (int i = 1; i <= JTa_SongsinPlaylist.getRowCount(); i++) {
                    JTa_SongsinPlaylist.remove(i);
                }*/
                JB_Song2Playlist.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_JB_SavePlaylistActionPerformed

    private void JB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_1ActionPerformed
        ListSong.setVisible(false);
        this.setVisible(true);
        this.pack();
    }//GEN-LAST:event_JB_1ActionPerformed

    private void JB_NewPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewPlaylistActionPerformed
        AddPlaylist.setVisible(true);
        AddPlaylist.pack();
        AddPlaylist.setLocationRelativeTo(null);
        ListSong.setVisible(false);
    }//GEN-LAST:event_JB_NewPlaylistActionPerformed

    private void Song2PlaylistTable() {
        int[] SelectedLine = JTa_AllSongs2.getSelectedRows();
        for (int i = 0; i < SelectedLine.length; i++) {
            Object[] Line = new Object[]{JTa_AllSongs2.getValueAt(SelectedLine[i], 0), JTa_AllSongs2.getValueAt(SelectedLine[i], 1), JTa_AllSongs2.getValueAt(SelectedLine[i], 2), JTa_AllSongs2.getValueAt(SelectedLine[i], 3), JTa_AllSongs2.getValueAt(SelectedLine[i], 4)};
            DefaultTableModel model = (DefaultTableModel) JTa_SongsinPlaylist.getModel();
            model.addRow(Line);
        }
    }

    private void Song2PlaylistsArrayList(ArrayList<Cancion> Songs) {
        TempSongs.removeAll(Songs);
        int[] SelectedLine = JTa_AllSongs2.getSelectedRows();
        for (int i = 0; i < SelectedLine.length; i++) {
            String Nom = (String) JTa_AllSongs2.getValueAt(SelectedLine[i], 0);
            String Art = (String) JTa_AllSongs2.getValueAt(SelectedLine[i], 1);
            String Alb = (String) JTa_AllSongs2.getValueAt(SelectedLine[i], 2);
            int Pun = Integer.parseInt(JTa_AllSongs2.getValueAt(SelectedLine[i], 3).toString());
            int Ano = Integer.parseInt(JTa_AllSongs2.getValueAt(SelectedLine[i], 4).toString());
            Cancion Song = new Cancion(Nom, Art, Alb, Pun, Ano);
            System.out.println(Song);
            Songs.add(Song);
        }
        JB_Song2Playlist.setVisible(false);
    }

    private void JB_Song2PlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Song2PlaylistActionPerformed
        if (JTa_AllSongs2.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una Cancion.");
        } else {
            try {
                DefaultTableModel TabModel = (DefaultTableModel) JTa_SongsinPlaylist.getModel();
                DefaultTableModel TabModel2 = (DefaultTableModel) JTa_AllSongs2.getModel();
                Song2PlaylistTable();
                Song2PlaylistsArrayList(TempSongs);
                this.JT_NombrePlaylsit.setText("PlayList");
                JOptionPane.showMessageDialog(null, "Agregada(s) a Playlist.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error.");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_JB_Song2PlaylistActionPerformed

    private void JB_EditPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EditPlayListActionPerformed
        AddPlaylist.setVisible(true);
        AddPlaylist.pack();
        AddPlaylist.setLocationRelativeTo(null);
        ListSong.setVisible(false);
    }//GEN-LAST:event_JB_EditPlayListActionPerformed

    private void JB_DeletePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DeletePlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_DeletePlaylistActionPerformed

    private void JMI_AbrirCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_AbrirCancionesActionPerformed

    }//GEN-LAST:event_JMI_AbrirCancionesActionPerformed

    private void JB_DeleteSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DeleteSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_DeleteSongActionPerformed


    private void JB_EditSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EditSongActionPerformed
        if (JTa_AllSongs.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Elija solo una cancion.");
        } else if (JTa_AllSongs.getSelectedRowCount() < 1) {
            JOptionPane.showMessageDialog(null, "Elija una cancion.");
        } else {
            SongMod(Songs.get(JTa_AllSongs.getSelectedRow()));
            AddSong.setVisible(true);
            AddSong.pack();
            AddSong.setLocationRelativeTo(null);
            ListSong.setVisible(false);
            JB_SaveSong.setVisible(false);
        }
    }//GEN-LAST:event_JB_EditSongActionPerformed

    private void JB_NewSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_NewSongActionPerformed
        AddSong.setVisible(true);
        AddSong.pack();
        AddSong.setLocationRelativeTo(null);
        ListSong.setVisible(false);
    }//GEN-LAST:event_JB_NewSongActionPerformed

    private void SongMod(Cancion Song) {
        JT_NombreSong.setText(Song.getNombre());
        JT_Artista.setText(Song.getArtista());
        JT_Album.setText(Song.getAlbum());
        int num = Song.getAño();
        JFT_Año.setText(String.valueOf(num));
        JCB_Puntos.setSelectedIndex(Song.getPuntos());
    }
    private void SongMod1(Cancion Song) {
        Song.setNombre(JT_NombreSong.getText());
        Song.setAlbum(JT_Album.getText());
        Song.setArtista(JT_Artista.getText());
        Song.setAño(Integer.parseInt(JFT_Año.getText()));
        Song.setPuntos(JCB_Puntos.getSelectedIndex());
                System.out.println(Songs);
Songs.get(JTa_AllSongs.getSelectedRow());
        System.out.println(Songs);
        Songss.WriteFileMod(Songs);
    }

    private void JB_SaveSongModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveSongModActionPerformed
        SongMod1(Songs.get(JTa_AllSongs.getSelectedRow()));
        JB_SaveSong.setVisible(true);
        ListSong.setVisible(true);
        ListSong.pack();
        ListSong.setLocationRelativeTo(null);
        AddSong.setVisible(false);
        JOptionPane.showMessageDialog(this, "Guardado Exitoso.");
        resetPersona();
    }//GEN-LAST:event_JB_SaveSongModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AddPlaylist;
    private javax.swing.JDialog AddSong;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JButton JB_1;
    private javax.swing.JButton JB_2;
    private javax.swing.JButton JB_3;
    private javax.swing.JButton JB_AddPlaylist;
    private javax.swing.JButton JB_AddSong;
    private javax.swing.JButton JB_DeletePlaylist;
    private javax.swing.JButton JB_DeleteSong;
    private javax.swing.JButton JB_EditPlayList;
    private javax.swing.JButton JB_EditSong;
    private javax.swing.JButton JB_NewPlaylist;
    private javax.swing.JButton JB_NewSong;
    private javax.swing.JButton JB_RemoveinPlaylist;
    private javax.swing.JButton JB_SavePlaylist;
    private javax.swing.JButton JB_SaveSong;
    private javax.swing.JButton JB_SaveSongMod;
    private javax.swing.JButton JB_Song2Playlist;
    private javax.swing.JButton JB_ViewPlaylist;
    private javax.swing.JButton JB_ViewSongs;
    private javax.swing.JComboBox<String> JCB_Puntos;
    private javax.swing.JFormattedTextField JFT_Año;
    private javax.swing.JMenuItem JMI_AbrirCanciones;
    private javax.swing.JMenuItem JMI_AbrirPlaylist;
    private javax.swing.JMenuItem JMI_VerCanciones;
    private javax.swing.JMenuItem JMI_VerPlaylists;
    private javax.swing.JTextField JT_Album;
    private javax.swing.JTextField JT_Artista;
    private javax.swing.JTextField JT_NombrePlaylsit;
    private javax.swing.JTextField JT_NombreSong;
    private javax.swing.JTable JTa_AllPlaylists;
    private javax.swing.JTable JTa_AllSongs;
    private javax.swing.JTable JTa_AllSongs2;
    private javax.swing.JTable JTa_SongsinPlaylist;
    private javax.swing.JDialog ListSong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
